dwmf/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('edit_user/', views.edit_user, name='edit_user'),
    path('profile/<int:user_id>/profile_photo/', views.profile_photo, name='profile_photo'),
    path('profile/<int:user_id>/delete_photo/', views.delete_photo, name='delete_photo'),
    path('trucks/<int:truck_id>/add_review/', views.add_review, name='add_review'),
    path('trucks/<int:truck_id>/review/<int:review_id>/delete_review/', views.delete_review, name='delete_review'),
    path('profile/<int:user_id>/assoc_truck/<int:truck_id>/', views.assoc_truck, name='assoc_truck'),
    path('profile/<int:user_id>/unnasoc_truck/<int:tk_id>/', views.unassoc_truck, name='unassoc_truck'),
    path('trucks/', views.trucks_index, name='index'),
    path('trucks/<int:truck_id>', views.trucks_info, name='index_detail'),
    path('truck/register/', views.TruckCreate.as_view(), name="truck_register"),
    path('truck/<int:truck_id>/', views.truck_detail, name='truck_detail'),
    path('truck/<int:truck_id>/create', views.menu_create, name='menu_create'),
    path('truck/<int:pk>/update', views.TruckUpdate.as_view(), name='truck_update'),
    path('truck/<int:truck_id>/reviews', views.truck_reviews, name='truck_reviews'),
    path('truck/<int:pk>/delete/', views.TruckDelete.as_view(), name='truck_delete'),
    path('truck/<int:truck_id>/truck_photo/', views.truck_photo, name='truck_photo'),
    path('truck/<int:truck_id>/truck_photo/delete/', views.delete_truck_photo, name='delete_truck_photo'),
    path('truck/<int:truck_id>/create/menu_new', views.menu_new, name='menu_new'),
    path('truck/<int:truck_id>/add_calendar', views.add_calendar, name='add_calendar'),
    path('truck/<int:truck_id>/calendar/<int:calendar_id>/delete', views.delete_calendar, name='delete_calendar'), 
    path('truck/<int:truck_id>/menu/<int:item_id>/menu_update', views.menu_update, name='menu_update'),
    path('truck/<int:truck_id>/menu/<int:item_id>/delete', views.delete_item, name='delete_item')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dwmf.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dwmf/models.py
from django.db import models
from django.urls import reverse
from datetime import date, time, timezone, datetime
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import Avg
import datetime



class Truck(models.Model):
    name = models.CharField(max_length=50)
    style = models.CharField(max_length=50)


    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('truck_detail', kwargs={'truck_id': self.id})



class Menu(models.Model):
    food_name = models.CharField(max_length=50)
    description = models.CharField(max_length=250)
    price = models.IntegerField()
    
    truck = models.ForeignKey(Truck, on_delete=models.CASCADE)
    print(truck)

    def __str__(self):
        return self.food_name
    
    def get_absolute_url(self):
        return reverse('truck_detail', truck_id=truck_id)

class Profile(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    truck_owner = models.BooleanField(default=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500)
    

    trucks = models.ManyToManyField(Truck)

    def __str__(self):
        return self.user.username

class ProfilePhoto(models.Model):
    url = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for profile picture: {self.user_id} @ {self.url}"

class TruckPhoto(models.Model):
    url = models.CharField(max_length=200)
    truck = models.ForeignKey(Truck, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for truck picture: {self.truck_id} @ {self.url}"

class Calendar(models.Model):
    date = models.DateField()
    start_time = models.CharField(max_length=50)
    end_time = models.CharField(max_length=50)
    location = models.CharField(max_length=250)

    truck = models.ForeignKey(Truck, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.date}, {self.start_time},{self.end_time}, {self.location}'
    
    def date_checker(self):
        date_check = date.today()
        return self.date < date_check
    
    def where_today(self):
        date_check = date.today()
        if date_check == self.date:
            return self

    class Meta:
        ordering = ['-date']

class Review(models.Model):
    text = models.TextField(max_length=500)
    created_date = models.DateTimeField()
    rating = models.IntegerField('Rating (1-5 allowed)', validators=[MinValueValidator(1), MaxValueValidator(5)], default=5)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    truck = models.ForeignKey(Truck, on_delete=models.CASCADE, related_name='reviews')

    def __str__(self):
        return f"{self.user.username} at {self.created_date}: {self.text} {self.rating}"


    def average(self):
        avg += self.rating
        print (avg)
        return avg

    class Meta:
        ordering = ['-created_date']

dwmf/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.db import models
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Profile, Menu, Calendar, Review, Truck



class ExtendedUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)  
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)  

    class Meta:
        model = User
        fields = ( 'first_name', 'last_name','username', 'email', 'password1', 'password2')

        def save(self, commit=True):
            user = super().save(commit=False)

            user.email = self.cleaned_data('email')
            user.first_name = self.cleaned_data('first_name')
            user.last_name = self.cleaned_data('last_name')

            if commit():
                user.save()
            return user


class EditUser(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            )
            
    def save(self, commit=True):
        user = super(EditUser, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
        
        return user


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ('text','rating',)



class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields= ('first_name', 'last_name') 

class MenuForm(ModelForm):
    class Meta:
        model = Menu
        fields =['food_name', 'description', 'price']

class CalendarForm(ModelForm):
    class Meta:
        model = Calendar
        fields = ['date', 'start_time', 'end_time', 'location']

class MenuUpdate(ModelForm):
    class Meta:
        model = Menu
        fields = ['food_name', 'description', 'price']

class TruckUpdate(ModelForm):
    class Meta:
        model = Truck
        fields = ['name', 'style']

    def save(self, commit=True):
        truck = super(TruckUpdate, self).save(commit=False)
        truck.name = self.cleaned_data['name']
        truck.style = self.cleaned_data['style']
        

        if commit:
            truck.save()
    
        return truck
       

dwmf/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Truck, User, Profile, Menu, Calendar, ProfilePhoto, TruckPhoto, Review
from .forms import ExtendedUserCreationForm, ProfileForm, MenuForm, CalendarForm, EditUser, ReviewForm, MenuUpdate, TruckUpdate
from datetime import date, time, timezone, datetime
from django.db.models import Avg
import uuid
import boto3



S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'dwmf'
# S3_BASE_URL = 'https://s3-us-east-2.amazonaws.com/'
# BUCKET = 'catcollector02'



#########################################
def home(request):
    return render(request, 'home.html')

##########################class views
class TruckCreate(LoginRequiredMixin, CreateView):
    model = Truck
    fields= ['name', 'style', ]
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class TruckUpdate(LoginRequiredMixin, UpdateView):
    model = Truck
    fields = ['name', 'style']

class TruckDelete(LoginRequiredMixin, DeleteView):
    model = Truck
    success_url = '/trucks/'
##########################view definitions here

@login_required
def truck_detail(request, truck_id):
    truck = Truck.objects.get(id=truck_id)
    calendar_form = CalendarForm()
    a = Review.objects.filter(truck_id=truck_id)
    sum = 0
    avg = 0

    if len(a) > 0:
        for rating in a:
            sum += rating.rating
            average = sum / len(a)  
            avg = str(round(average, 1))
    return render(request, 'dwmf/truck_detail.html', {
        'truck': truck,
        'calendar_form': calendar_form,
        'avg':avg
        })

@login_required
def menu_create(request, truck_id):
    truck = Truck.objects.get(id=truck_id)
    menu_form = MenuForm()

    return render(request, 'dwmf/menu_form.html',{'truck':truck, 'menu_form': menu_form})

@login_required
def menu_new(request, truck_id):
    truck = Truck.objects.get(id=truck_id)
    form = MenuForm(request.POST)

    if form.is_valid():
        new_menu = form.save(commit=False)
        new_menu.truck_id = truck.id
        new_menu.save()
    return redirect('truck_detail', truck_id=truck_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = ExtendedUserCreationForm(request.POST)
        profile_form = ProfileForm(request.POST)

        if form.is_valid() and profile_form.is_valid():
            user = form.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            profile.save()
           
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)

            return redirect('index')
        else:
            error_message = 'Invalid Signup - Please try again'
    form = ExtendedUserCreationForm()
    profile_form = ProfileForm()
    context = {'form': form, 'profile_form': profile_form,'error_message': error_message}
    return render(request, 'registration/signup.html', context)

@login_required
def profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
        profile = request.user.profile
    trucks = Truck.objects.all()
    trucks_user_doesnt_favorite = Truck.objects.exclude(id__in = profile.trucks.all().values_list('id'))
    truck = trucks.first()
    return render(request, 'registration/profile.html', {'user': user, 'trucks': trucks, 'trucks_user_doesnt_favorite': trucks_user_doesnt_favorite})

@login_required
def profile_photo(request, user_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = ProfilePhoto(url=url, user_id=user_id)
            photo.save()
        except:
            print('An error occurred uploading the file to the cloud')
    return redirect(reverse('profile'))

@login_required
def delete_photo(request, user_id):
    key = ProfilePhoto.objects.get(user_id=user_id)
    key.delete()
    
    return redirect(reverse('profile'))

@login_required
def delete_truck_photo(request, truck_id):
    key = TruckPhoto.objects.get(truck_id=truck_id)
    key.delete()
    
    return redirect('truck_detail', truck_id=truck_id) 

@login_required
def truck_photo(request, truck_id):

    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = TruckPhoto(url=url, truck_id=truck_id)
            photo.save()
        except:
            print('An error occurred uploading the file to the cloud')
    return redirect('truck_detail', truck_id=truck_id)

@login_required
def assoc_truck(request, user_id, truck_id):
    Profile.objects.get(user_id=user_id).trucks.add(truck_id)
    return redirect(reverse('profile'))

@login_required
def unassoc_truck(request, user_id, tk_id):
    Profile.objects.get(user_id=user_id).trucks.remove(tk_id)
    return redirect(reverse('profile'))

def trucks_index(request):
    trucks = Truck.objects.all()
    t = trucks.first()
    print(t.reviews.all())
    return render(request, 'trucks/index.html', {'trucks': trucks })

def trucks_info(request, truck_id):
    truck = Truck.objects.get(id=truck_id)
    review_form = ReviewForm()
    a = Review.objects.filter(truck_id=truck_id)
    sum = 0
    if len(a) > 0:
        for rating in a:
            sum += rating.rating
        average = sum / len(a)  
        avg = str(round(average, 1))
    else: 
        avg = 'None: Be the first to review!'
    return render(request, 'trucks/index_detail.html', {'truck': truck, 'review_form': review_form, 'avg': avg})

@login_required
def add_review(request, truck_id):
    form = ReviewForm(request.POST)
    user = request.user
    if form.is_valid():
        new_review = form.save(commit=False)
        new_review.truck_id = truck_id
        new_review.user_id = user.id
        new_review.created_date = datetime.now()
        new_review.save()
    return redirect('index_detail', truck_id=truck_id)

@login_required
def truck_reviews(request, truck_id):
    reviews = Review.objects.filter(truck=truck_id)
    truck = Truck.objects.get(id=truck_id)
    return render(request, 'dwmf/truck_reviews.html', {'reviews':reviews, 'truck': truck})

@login_required
def delete_review(request, truck_id, review_id):
    review = Review.objects.get(id=review_id)
    if request.method == 'POST':
        review.delete()
        return redirect('index_detail', truck_id=truck_id)
    else:
        return render(request, 'trucks/index_detail.html', truck_id=truck_id)

@login_required
def add_calendar(request, truck_id):
   
    form = CalendarForm(request.POST)

    if form.is_valid():

        new_calendar = form.save(commit=False)
        new_calendar.truck_id = truck_id
        new_calendar.save()
    return redirect('truck_detail', truck_id=truck_id)

@login_required
def edit_user(request):
    if request.method == 'POST':
        form = EditUser(request.POST, instance=request.user)
        

        if form.is_valid():
            form.save()
            return redirect('/profile')
    else:
        form = EditUser(instance=request.user)
        return render(request, 'registration/edit_user.html', {'form': form}) 

@login_required
def menu_update(request, item_id, truck_id):
    item = Menu.objects.get(id=item_id)
    if request.method == 'POST':
        form = MenuUpdate(request.POST, instance=item)

        if form.is_valid():
            update_item = form.save(commit=False)
            update_item.truck_id = truck_id
            update_item.save()
            return redirect('truck_detail', truck_id=truck_id)
    else:
        form = MenuUpdate(instance=item)
        return render(request, 'dwmf/menu_update.html',{'form': form})

@login_required
def delete_item(request, item_id, truck_id):
    obj = Menu.objects.get(id=item_id)
    if request.method == 'POST':
        obj.delete()
        return redirect('truck_detail', truck_id=truck_id)
    context ={
        truck_id: truck_id,
    }
    return render(request, 'dwmf/truck_detail.html', {'truck_id': truck_id})

@login_required
def delete_calendar(request, calendar_id, truck_id):
    obj = Calendar.objects.get(id=calendar_id)
    if request.method == 'POST':
        obj.delete()
        return redirect('truck_detail', truck_id=truck_id)
    context ={
        truck_id: truck_id,
    }
    return render(request, 'dwmf/truck_detail.html', {'truck_id': truck_id})

dwmf/templates/dwmf/menu_form.html
{%extends 'base.html'%}

{%block content%}
<div class="container" id="create-menu">
    <h1 class="center create-menu-h1">Create a Menu Item</h1>

    <form action="{% url 'menu_new' truck.id%}" method="post">
        
        {%csrf_token%}
        <table>
            {{menu_form.as_p}}
        </table>
        <input type="submit" value="Register" class="btn create-menu-btn">
    </form>
</div>
{%endblock%}

dwmf/templates/dwmf/menu_update.html
{%extends 'base.html'%}

{%block content%}
<div class="container" id="update-menu">
    <h1 class="center update-menu-h1">Update Menu Item</h1>
    <form action="" method="post">
        {%csrf_token%}
        {{form.as_p}}
        <input class="btn update-menu-btn" type="submit" value ='update' name="" id="">
    </form>
</div>
{%endblock%}

dwmf/templates/dwmf/truck_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container" id="delete-truck">
  <h1 class="center delete-truck-h1">Delete Your Truck?</h1>

  <h4>Are you sure you want to delete <span class="black-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn center delete-truck-btn">
    <a href="{% url 'truck_detail' truck.id %}">Cancel</a>
  </form>
</div>
{% endblock %}

dwmf/templates/dwmf/truck_detail.html
{% extends 'base.html' %}
{% block content %}


<div class="row">

 <!-- Left side bar -->
    <div class="col s3">

        <!-- Row One -->

        <div class="row">
            <h2 class="center truck-detail-h2">{{truck.name}}</h2>
            <h6 class="center">Owner:{{truck.user.first_name}} {{truck.user.last_name}}</h6>
        </div>

        <!--Row 2  -->

        <div class="row">    
            <div class="container">
                {% for photo in truck.truckphoto_set.all %}
                    <img class="truck-profile" src="{{photo.url}}">
                {% empty %}
                    <div>No Photos Uploaded</div>
                {% endfor %}
                {% if truck.truckphoto_set.all|length == 0%}
                    <form action="{% url 'truck_photo' truck.id %}" enctype="multipart/form-data" method="POST">
                        {% csrf_token %}
                        <input type="file" name="photo-file">
                        <br><br>
                        <input type="submit" class="btn" value="Upload Photo">
                    </form>
                {% else%}
                    <form action="{% url 'delete_truck_photo' truck.id %}" method="POST">
                        {% csrf_token %}
                        <input type="submit" class="btn" value="Delete Photo">
                    </form> 
                {% endif %}
                <a href="{%url 'truck_update' truck.pk%}">Edit Truck Profile</a>
                <br>
                <a href="{% url 'truck_delete' truck.pk %}">Delete Truck</a>
            </div>
        </div>
       
        <!-- Row 3 -->
        <div class="row">
            <div class="container">
                <h5 class="view-review-h3"><span class="yellow-text"> My Overall <br>Review</span>: {{avg}}</h5>
                <a href="{%url 'truck_reviews' truck.id%}">My Reviews</a>
            </div>  
        </div>
    </div>


<!-- Right Side Bar -->
    <div class="col s9">

      <!-- Calendar container and informations -->
        <div class="row">
            <div class="container">
                <div class="col s6">
                    <div class="container add-calendar">
                        <h3 class="center calendar-h1">New Calendar Date</h3>
                        <form action="{%url 'add_calendar' truck.id%}" method="post" style="color: black;">
                            {%csrf_token%}
                            {{calendar_form.as_p}}
                            <input type="submit" class="btn calendar-btn" value="Add Date">
                        </form>
                    </div>
                </div>                
                <div class="col s6">
                    <h1 class="calendar-h1">Your Calendar</h1>
                    <hr>
                    {%if truck.calendar_set.count%}
                        {%for calendar in truck.calendar_set.all%}
                            {%if calendar.date_checker%}

                            {%else%}
                            <div class="container col s6" >
                                <ul class="left calendar-ul">
                                    <li id="calendar-holder"><span class="black-text">Date</span>: {{calendar.date}}</li>
                                    <li id="calendar-holder"><span class="black-text">Start Time</span>: {{calendar.start_time}}</li>  
                                    <li id="calendar-holder"><span class="black-text">End Time</span>: {{calendar.end_time}}</li>
                                    <li id="calendar-holder">{{calendar.location}}</li>
                                    <li class="center" id="calendar-holder"><form action="{% url 'delete_calendar' truck.id calendar.id %}" method="post">
                                        {% csrf_token %}
                                    <button type="submit" class="btn center">Remove</button>
                                    </form></li>
                                </ul>
                            </div>
                            {%endif%}
                        {%endfor%}
                    {%else%}
                        <h1>You have no upcoming dates</h1>
                    {%endif%}
                </div>
            </div>
        </div>
    </div>
</div>
 <!-- Menu Items! -->
<div class="row ">
    <div class="container">
        <h1 class="center menu-h1">Menu Items</h1><hr>
        <a href="{%url 'menu_create' truck.id%}">Create Menu Item</a>
        <div class="row">
        {%for item in truck.menu_set.all%}
            <div class="col s12 m6 l4">
                <div class="card" id="menu-card">
                    <div class="card-content"> 
                        <form action="{% url 'delete_item' truck.id item.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn right">Remove</button>
                        </form>
                        <a class="right" href="{%url 'menu_update'  truck.id item.id%}">Update Item</a>
                        <p><span class="card-title">{{item.food_name}}</span></p>
                        <hr>
                        <p>{{item.description}}</p>
                        <p>${{item.price}}</p>
                    </div>    
                </div>
            </div>
        {%endfor%}
        </div>
    </div>
</div>
    




<!-- Scrpit for date and timepicker -->
<script>
    // create a datepicker
    var dateEl = document.getElementById('id_date');
    console.log(dateEl)
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
    });
    
    var start = document.getElementById('id_start_time');
    M.Timepicker.init(start, {
        defaultTime: 'now',
        autoClose: true
    });
    var end = document.getElementById('id_end_time');
    M.Timepicker.init(end, {
        defaultTime: 'now',
        autoClose: true
    });
  </script>
{% endblock %}

dwmf/templates/dwmf/truck_form.html
{% extends 'base.html'%}

{% block content %}
    <div class="container" id="create-truck">
    {%if object%}
        <h1 class="center update-truck">Edit <span class="black-text">{{truck.name}}</span></h1>
    {%else%}
    <h1 class="center create-truck">Register Your Food Truck</h1>
    {%endif%}
    <form action="" method="post">
        {%csrf_token%}
        <table>
            {{form.as_p}}
        </table>
        <input type="submit" value="Submit" class="btn create-truck-btn">
    </form>
    </div>

{% endblock%}

dwmf/templates/dwmf/truck_reviews.html
{%extends 'base.html'%}

{%block content%}
    
<div class="container">
  <div class="row">
    <div class="col s12">
    <h1 class="center truck-review-h1">Reviews for <span class="red-text">{{truck.name}}</span></h1>
      {%for review in reviews.all%}
    
      <ul class="collection col s12 m8 push-m2" id="review-ul">
          <li class="collection-item avatar">
          {%for photo in review.user.profilephoto_set.all%}
            <img src="{{photo.url}}" alt="" class="circle">
          {%endfor%}
            <p><span class="title">User:</span> {{review.user}}  
            <span class="title">Rating:</span> {{review.rating}}</<span> 
            <p><span class="title"> Date:</span> {{review.created_date}}</p>

            <p>{{review.text}}</p>
            </Rating:>
          </li>
      </ul>
      {%endfor%}
    </div>
  </div>    
</div>
{%endblock%}